language: c
os:
 - linux
 - osx
env:
 matrix:
  - PYTHON_VERSION=2.7
  - PYTHON_VERSION=3.6
  - PYTHON_VERSION=3.7
before_install:
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get update; fi
  - if [[ $TRAVIS_OS_NAME == linux ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment -c conda-forge python=$PYTHON_VERSION jupyter_server==0.0.5 jupyterlab_pygments==0.1.0 pytest==3.10.1 pytest-cov nodejs flake8 ipywidgets
  - source activate test-environment
install:
  - pip install ".[test]"
  # we need this branch to perform testing, do it after the pip install above, otherwise we 'downgrade'
  - pip install --upgrade --no-deps --force-reinstall git+https://github.com/jupyter/nbconvert.git@master#egg=nbconvert
before_script:
  - flake8 voila
script:
  - VOILA_TEST_DEBUG=1 py.test tests/
